apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: testproytribu-tk-tls
spec:
  secretName: testproytribu-tk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: testproytribu.tk
  dnsNames:
    - testproytribu.tk
    - www.testproytribu.tk
